---
title: "Emus nuclei script"
output: html_notebook
  
editor_options: 
  chunk_output_type: console
---


```{r}
library(tidyverse)
library(viridis)
library(grid)
library(gridExtra)

```



```{r}
E.nuc <- read.csv("Emusc_nuclei.csv")

phylo=c("E. muscae KVL14-117",
        "E. ferdinandii, E. muscae ARSEF 6132",
        "E. muscae ARSEF 6716",
        "E. muscae ARSEF 13514",
        "E. muscae ARSEF 6815",
        "E. muscae ARSEF 3074",
        "E. muscae ARSEF 6918",
        "E. scatophaga ARSEF 6704",
        "E. grandis, E. sp.  ARSEF 6701",
        "E.  sp. SoCal cadaver 1",
        "E. syrphi ARSEF 5955 (deposited as 5595)",
        "E. schizophorae ARSEF 6137",
        "E. sp. LTE cadaver 1",
        "E. schizophorae ARSEF 6817")

E.nuc2 = E.nuc %>%
  filter(Source=="Phylogenetics") %>%
  mutate(Strain=as.factor(Strain)) %>%
  mutate(Strain=factor(Strain, levels=rev(phylo)))

plt1=ggplot(E.nuc2, aes(x=Average, y=Strain), color="black")+geom_point(size=3)+geom_errorbar(aes(xmin=Min, xmax=Max), size=2)+theme_bw()+xlab("Nuclei")+theme(text=element_text(size=20), legend.position="none")+ylab("")+xlim(0,50)+theme(axis.ticks.length=unit(-0.25, "cm"))+xlab("Number of nuclei (primary conidia)")

plt1

E.nuc.host=E.nuc %>%
  filter(Source=="Phylogenetics") %>%
  select(Strain, Host, Family, Order, Genus, Superfamily, Species) %>%
  group_by(Species, Strain) %>%
  pivot_longer(cols=Host:Superfamily, names_to="Classification", values_to="Name") %>%
  filter(Classification!="Host" & Classification!="Genus") %>%
  mutate(Classification=as.factor(Classification)) %>%
  mutate(Classification=factor(Classification, levels=levels(Classification)[c(2,3,1)])) %>%
   mutate(Strain=as.factor(Strain)) %>%
  mutate(Strain=factor(Strain, levels=rev(phylo)))

E.nuc.host$Name=as.factor(E.nuc.host$Name)
E.nuc.host$Name=factor(E.nuc.host$Name, levels=c(unique(E.nuc.host[E.nuc.host$Classification=="Order",]$Name),
unique(E.nuc.host[E.nuc.host$Classification=="Superfamily",]$Name),
unique(E.nuc.host[E.nuc.host$Classification=="Family",]$Name)))

plt2=ggplot(subset(E.nuc.host, Classification=="Family"), aes(x=Classification, y=Strain, fill=Name))+geom_tile()+scale_fill_viridis_d(option="E")+theme_bw()+xlab("Nuclei")+theme(text=element_text(size=15), legend.position="none", axis.text.y=element_blank())+ylab("")+xlab("")+scale_x_discrete(guide=guide_axis(angle=90))+theme(axis.ticks.length=unit(-0.25, "cm"))

grob1=ggplotGrob(plt1)
grob2=ggplotGrob(plt2)

maxHeights <- unit.pmax(grob1$heights, grob2$heights)

grob1$heights= maxHeights
grob2$heights= maxHeights

layout <- rbind(c(1:2))

grid.arrange(grob1, grob2, layout_matrix=layout, widths=c(0.9, 0.1))

```

```{r}
E.con <- read.csv("Emus conidial metrics updated.csv")

E.con2 = E.con %>%
  pivot_longer(cols=Mean:Max, names_to="Metric2", values_to="Value") %>%
  pivot_wider(names_from=c("Metric", "Metric2"), values_from="Value") %>%
  mutate(Species=as.factor(Species)) %>%
  mutate(Species=factor(Species, levels=levels(Species)[c(1,10,2,9,3:8)]))
  
theme = theme_bw()+theme(text = element_text(size=15), axis.title.x = element_text(size=20), axis.title.y = element_text(size=20), axis.text.x = element_text(size=20), axis.text.y = element_text(size=20), title = element_text(size=35), legend.title = element_text(size=15))

plt3=ggplot(E.con2)+
  geom_rect(aes(ymin=Length_Mean-Length_Difference, ymax=Length_Mean+Length_Difference, xmin=Width_Mean-Width_Difference, xmax=Width_Mean+Width_Difference, fill=Species), alpha=0.5)+
  geom_point(aes(x=Width_Mean, y=Length_Mean, color=Species), size=4)+
  geom_point(aes(x=Width_Mean, y=Length_Mean), color="white", size=2)+
  theme_bw()+scale_color_viridis_d()+
  scale_fill_viridis_d()+
  theme(text=element_text(size=15))+ylab("Length")+xlab("Width")+expand_limits(x=15:33, y = 15:33)+coord_fixed(ratio = 1)+
  ggrepel::geom_label_repel(aes(x=Width_Mean, y=Length_Mean, label=Species, color=Species))+
  guides(color="none")+theme(axis.ticks.length=unit(-0.25, "cm"))+theme

plt3

```


```{r}
Rep.nuc <- read.csv("Emus nuclei metrics.csv")

plt4=ggplot(Rep.nuc, aes(x=reorder(Species, -Max), y=Mean, ymin=Min, ymax=Max, color=Species))+
  geom_linerange(size=3)+coord_flip()+theme_bw()+scale_color_viridis_d(limits=levels(E.con2$Species), option="C")+ylim(0,50)+theme(text=element_text(size=20), legend.position="none")+theme(axis.ticks.length=unit(-0.25, "cm"), axis.title.x=element_blank(), axis.title.y=element_blank())

plt4

grob1=ggplotGrob(plt1)
grob2=ggplotGrob(plt2)
grob3=ggplotGrob(plt4)

maxHeights <- unit.pmax(grob1$heights, grob2$heights)

grob1$heights= maxHeights
grob2$heights= maxHeights

maxWidths <- unit.pmax(grob1$widths, grob3$widths)

grob1$widths= maxWidths
grob3$widths= maxWidths

layout <- rbind(c(3, NA),c(1:2))

grid.arrange(grob1, grob2, grob3, layout_matrix=layout, heights=c(0.2,0.8), widths=c(0.9, 0.1))

```

